<?php

require_once 'userModel.php';
require_once 'DonationManager.php';

class Admin extends User{
    private int $adminID; 
    private DonationManager $donationManager; 

    public function __construct(int $adminID,float $goalAmount = 0.0) {
        $this->adminID = $adminID;
        $this->donationManager = new DonationManager($goalAmount = 0.0, $donations = [], $campaigns = []);
    }

    public function manageUsers(int $userID): void {
        echo "Managing user with ID: $userID\n";
        $user = new User("username", "First", "Last", $userID, "user@example.com", "usernameID", "password", [], "phoneNumber");
        $user -> update($userID);
    }

    public function generateReports(): string {
        $totalDonations = $this->donationManager->calculateTotalDonations();
        return "Report generated by Admin ID: $this->adminID. Total Donations: $totalDonations";
    }

    public function sendNotification(int $userID): void {
        //IMPLEMENTATION LESA HENAAA
        echo "Notification sent to user with ID: $userID\n";
    }
    //TTFHEMMMM
    public function viewDonationStatistics(): string {
        $statistics = [];
        foreach ($this->donationManager->generateDonationReport() as $donation) {
            $statistics[] = $this->donationManager->getDonationStatistics($donation);
        }
        return "Donation statistics viewed by Admin ID: $this->adminID:\n" . implode("\n", $statistics);
    }
}

// Example usage
$admin = new Admin(1);
$admin->manageUsers(2);
echo $admin->generateReports() . "\n";
$admin->sendNotification(2);
echo $admin->viewDonationStatistics() . "\n";

?>
